name: CI/CD Pipeline

on:
  push:
    branches: [main, staging, local]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. DÃ©finition des variables (utilisables dans les steps suivants via $TAG et $API_URL)
      - name: Set Environment Variables
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "TAG=prod" >> $GITHUB_ENV
            echo "REACT_APP_API_BASE_URL=https://mvp-backend-prod-latest.onrender.com" >> $GITHUB_ENV
          else
            echo "TAG=staging" >> $GITHUB_ENV
            echo "REACT_APP_API_BASE_URL=https://mvp-backend-staging-latest.onrender.com" >> $GITHUB_ENV
          fi

      # 3. Build & Push (Back et Front)
      - name: Build and Push Images
        run: |
          # Backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mvp-back:${{ env.TAG }} ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mvp-back:${{ env.TAG }}

          # Frontend
          docker build --build-arg REACT_APP_API_BASE_URL="${{ env.API_URL }}" \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mvp-front:${{ env.TAG }} ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mvp-front:${{ env.TAG }}

      # 4. Deploy Front (Google Cloud Run)
      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy front-${{ env.TAG }} \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mvp-front:${{ env.TAG }} \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated

      # 5. Deploy Back (Render via Webhook)
      - name: Deploy Backend to Render
        run: |
          if [[ "${{ env.TAG }}" == "prod" ]]; then
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PROD }}
          else
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}
          fi
